spring:
  application:
    name: quizme
  data:
    mongodb:
      uri: mongodb://localhost:27017/quizme
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  devtools:
    restart:
      enabled: true
      additional-paths: 
        - src/main/resources
        - src/main/java
      poll-interval: 1000
      quiet-period: 400
    livereload:
      enabled: true
      port: 35729
    remote:
      secret: mysecret

server:
  undertow:
    threads:
      worker: 8
      io: 2
    buffer-size: 1024
    direct-buffers: true