spring:
  application:
    name: webscraper
  datasource:
    url: jdbc:sqlite:data/webscraper.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  devtools:
    restart:
      enabled: true
      additional-paths: 
        - src/main/resources
        - src/main/java
      poll-interval: 1000
      quiet-period: 400
    livereload:
      enabled: true
      port: 35729
    remote:
      secret: mysecret
